### ISSUE TITLE
Course 1 Assessment: Introduction to Web Development - errors

### ISSUE THREAD

**Issue by johnfelipe** [dennislamcv1/MetaFrontEnd#1]
attempt 1:

![SNAG-0121](https://user-images.githubusercontent.com/428820/195897939-44d86664-da6e-4ffd-8d6f-e230e9ea2308.png)

attempt 2:

![SNAG-0122](https://user-images.githubusercontent.com/428820/195898123-20d3543c-928e-4887-825d-a9f6b6fc5e48.png)

attempt 3:

![SNAG-0123](https://user-images.githubusercontent.com/428820/195898359-e23d6b8f-a908-405d-bb70-2a1111858d26.png)

attempt 4:

![SNAG-0142](https://user-images.githubusercontent.com/428820/195965516-d5b089c7-ceb1-4c42-a58a-c763b07ea22a.png)

for any user will use

**Comment by dennislamcv1** [comment]
Hey John, I am not completing this whole program. Just doing for fun.

The final exam has questions changed every time, you need to compare each screenshots.

The programming grading sucks just like other META programs I did.

**Comment by dennislamcv1** [comment]
Roger and out
