### ISSUE TITLE
Introduction to Front-End Development/Create and style a webpage - missing

### ISSUE THREAD

**Issue by johnfelipe** [dennislamcv1/MetaFrontEnd#2]
The following tests failed:

✗ There should be a stylesheet <link> tag in the <head> tag (+ 2 related tests)
✗ There should be 5 <div> tags in the <body>
✗ The 3rd <div> tag should have a <ul> tag (+ 2 related tests)
✗ The 4th <div> tag should have an <h2> tag (+ 2 related tests)
✗ The 4th <div> tag should have a <ol> tag (+ 2 related tests)
✗ The 5th <div> tag should have an <a> tag (+ 2 related tests)

**Comment by dennislamcv1** [comment]
You can find the answer in the discussion forum ( look at week XXX ).

**Comment by johnfelipe** [comment]
> You can find the answer in the discussion forum ( look at week XXX ).

can u refer url?
