### ISSUE TITLE
Building an object-oriented program still with errors

### ISSUE THREAD

**Issue by johnfelipe** [dennislamcv1/MetaFrontEnd#6]
pls help me with this

**Comment by dennislamcv1** [comment]
Not taking this whole spec

**Comment by dennislamcv1** [comment]
I am currently updating the Javascript corrections file

**Comment by dennislamcv1** [comment]
All done.

**Comment by dennislamcv1** [comment]
I have added the Final Capstone project answer except the project files as not sure how to do.
